{
 "title": "API Monitoring Dashboard",
 "tags": [ "api-monitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "95P-Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_response_time_bucket[25m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median API response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_response_time_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "api_request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Real-Time Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api_logs\"}"
    }
   ]
  }
 ]
}