{
 "title": "API Monitoring Dashboard",
 "tags": [
  "real-time",
  "logs",
  "api-monitoring",
  "errors",
  "metrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "api_request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "95P-Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_response_time_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median API response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_response_time_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real-Time Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api_logs\"}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(api_error_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(status_code) (api_error_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real-Time Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"api_logs\"}"
    }
   ]
  }
 ]
}