{
 "title": "Error Metrics Dashboard",
 "tags": [
  "errors",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error distribution (by status code)",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_error_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(api_error_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (api_error_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}